[package]
name = "voxel"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
noise = "0.9.0"
pollster = "0.3.0"
rand = "0.8.5"
wgpu = { version = "22.0.0", features = ["vulkan-portability"] }
winit = "0.30.4"
svo = { path = "../svo" }
